// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';

export function Connect(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetState():Promise<agent.State>;

export function GetVersion():Promise<string>;

export function SelectDirectory():Promise<string>;
