// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {agent} from '../models';

export function CheckEnvironment():Promise<main.EnvStatus>;

export function Connect(arg1:string,arg2:string,arg3:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetACPAgents():Promise<Array<main.ACPAgent>>;

export function GetNPMInstallGuide():Promise<string>;

export function GetState():Promise<agent.State>;

export function GetVersion():Promise<string>;

export function OpenURL(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetACPRunner(arg1:string):Promise<void>;

export function TerminalClose():Promise<void>;

export function TerminalResize(arg1:number,arg2:number):Promise<void>;

export function TerminalRunCommand(arg1:string):Promise<void>;

export function TerminalStart():Promise<void>;

export function TerminalWrite(arg1:string):Promise<void>;
