// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckEnvironment() {
  return window['go']['main']['App']['CheckEnvironment']();
}

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetACPAgents() {
  return window['go']['main']['App']['GetACPAgents']();
}

export function GetNPMInstallGuide() {
  return window['go']['main']['App']['GetNPMInstallGuide']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetACPRunner(arg1) {
  return window['go']['main']['App']['SetACPRunner'](arg1);
}

export function TerminalClose() {
  return window['go']['main']['App']['TerminalClose']();
}

export function TerminalResize(arg1, arg2) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2);
}

export function TerminalRunCommand(arg1) {
  return window['go']['main']['App']['TerminalRunCommand'](arg1);
}

export function TerminalStart() {
  return window['go']['main']['App']['TerminalStart']();
}

export function TerminalWrite(arg1) {
  return window['go']['main']['App']['TerminalWrite'](arg1);
}
