// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
